# Generated by Django 5.0.6 on 2024-06-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2500)),
                ('location', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('products', models.TextField()),
                ('social_media_links', models.URLField(blank=True)),
                ('website_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idohandmade_markets.marketevent')),
            ],
        ),
    ]
