# Generated by Django 5.0.6 on 2024-06-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idohandmade_markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketevent',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
