# Generated by Django 5.0.6 on 2024-06-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idohandmade_markets', '0002_marketevent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='contact_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
