# Generated by Django 5.0.6 on 2024-06-20 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idohandmade_markets', '0003_vendorapplication_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketevent',
            name='date',
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('market_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idohandmade_markets.marketevent')),
            ],
        ),
    ]
