# Generated by Django 5.0.6 on 2024-06-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idohandmade_markets', '0004_remove_marketevent_date_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
