# Generated by Django 5.0.6 on 2024-06-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idohandmade_markets', '0005_eventdate_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketevent',
            name='price',
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='market_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_dates', to='idohandmade_markets.marketevent'),
        ),
    ]
