# Generated by Django 5.0.6 on 2024-07-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idohandmade_markets', '0006_remove_marketevent_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketevent',
            name='event_type',
            field=models.TextField(default='', max_length=60),
        ),
    ]
