# Generated by Django 5.0.6 on 2024-07-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idohandmade_markets', '0007_marketevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketevent',
            name='event_type',
            field=models.CharField(default='', max_length=60),
        ),
    ]
